@extends('layouts.public')
@section('title', 'Kebijakan Privasi | Jokiinlah')
@section('description', 'Kebijakan pemrosesan dan perlindungan data untuk layanan Pendampingan Akademik & Digital Jokiinlah.')
@section('content')
<header class='bg-navy py-16 text-white'><div class='container-public max-w-4xl'><h1 class='text-4xl font-bold sm:text-5xl'>Kebijakan Privasi</h1><p class='mt-5 leading-8 text-white/75'>Versi {{ $version }}. Dokumen ini menjelaskan data yang kami proses ketika Anda mengajukan konsultasi.</p></div></header>
<section class='section-space'><article class='container-public surface-card safe-content max-w-4xl space-y-9 p-7 sm:p-12'>
    <section><h2 class='text-2xl font-bold text-navy'>Data yang dikumpulkan</h2><p class='mt-3 leading-8 text-muted'>Kami memproses identitas dan kontak, pilihan layanan, rincian kebutuhan, target waktu, estimasi anggaran opsional, serta dokumen yang Anda unggah. Jangan mengirim password, API key, credential, atau data sensitif yang tidak diperlukan.</p></section>
    <section><h2 class='text-2xl font-bold text-navy'>Tujuan pemrosesan</h2><p class='mt-3 leading-8 text-muted'>Data digunakan untuk memeriksa kebutuhan, menghubungi Anda, menjaga keamanan layanan, mencegah penyalahgunaan, serta memenuhi kewajiban operasional dan hukum yang berlaku. Pengajuan konsultasi tidak membuat akun pelanggan secara otomatis.</p></section>
    <section><h2 class='text-2xl font-bold text-navy'>Penyimpanan dan akses</h2><p class='mt-3 leading-8 text-muted'>Lampiran disimpan pada private storage dengan nama internal acak dan tidak tersedia melalui URL publik. Konsultasi awal hanya dikelola admin. Akses staff baru diberikan setelah konsultasi menjadi proyek dan staff ditugaskan.</p></section>
    <section><h2 class='text-2xl font-bold text-navy'>Retensi dan keamanan</h2><p class='mt-3 leading-8 text-muted'>Data disimpan selama diperlukan untuk tujuan layanan, audit, keamanan, dan kewajiban hukum. Jadwal retensi dapat berbeda menurut jenis data. ZIP dan RAR hanya disimpan sebagai lampiran privat serta tidak diekstrak atau dijalankan aplikasi.</p></section>
    <section><h2 class='text-2xl font-bold text-navy'>Hak dan kontak</h2><p class='mt-3 leading-8 text-muted'>Anda dapat meminta koreksi atau informasi mengenai data yang dikirim melalui halaman kontak. Permintaan penghapusan akan ditinjau terhadap kebutuhan retensi, keamanan, audit, dan kewajiban hukum.</p></section>
    <section><h2 class='text-2xl font-bold text-navy'>Email dan WhatsApp</h2><p class='mt-3 leading-8 text-muted'>Kontak digunakan untuk menanggapi konsultasi dan komunikasi layanan yang Anda minta. WhatsApp adalah layanan pihak ketiga dengan kebijakannya sendiri; hindari mengirim data yang tidak diperlukan melalui kanal tersebut.</p></section>
    <section><h2 class='text-2xl font-bold text-navy'>Perubahan kebijakan</h2><p class='mt-3 leading-8 text-muted'>Versi dan tanggal kebijakan akan diperbarui ketika terdapat perubahan material. Versi yang disetujui saat pengajuan dicatat bersama konsultasi.</p></section>
    <aside class='rounded-2xl border border-gold/30 bg-gold/10 p-5 text-sm leading-7 text-charcoal'><strong>Perlu dilengkapi sebelum production:</strong> identitas badan/pengelola, alamat korespondensi, email privasi resmi, dan periode retensi final harus ditinjau dan dikonfirmasi.</aside>
</article></section>
@endsection
