@extends('layouts.public')
@section('title', 'Syarat dan Ketentuan | Jokiinlah')
@section('description', 'Syarat penggunaan layanan konsultasi akademik, analisis data, editing, dan pengembangan aplikasi Jokiinlah.')
@section('content')
<header class='bg-navy py-16 text-white'><div class='container-public max-w-4xl'><h1 class='text-4xl font-bold sm:text-5xl'>Syarat dan Ketentuan</h1><p class='mt-5 leading-8 text-white/75'>Versi {{ $version }}. Penggunaan layanan tunduk pada ruang lingkup yang disepakati dan prinsip integritas akademik.</p></div></header>
<section class='section-space'><article class='container-public surface-card safe-content max-w-4xl space-y-9 p-7 sm:p-12'>
    <section><h2 class='text-2xl font-bold text-navy'>Karakter layanan</h2><p class='mt-3 leading-8 text-muted'>Jokiinlah menyediakan konsultasi, pendampingan pembelajaran dan metodologi, editing, analisis data yang sah, serta pengembangan solusi digital. Informasi awal bukan quotation, jaminan publikasi, jaminan kelulusan, atau jaminan hasil bisnis.</p></section>
    <section><h2 class='text-2xl font-bold text-navy'>Integritas akademik</h2><p class='mt-3 leading-8 text-muted'>Kami melarang plagiarisme, ghostwriting untuk diserahkan sebagai karya mandiri, fabrikasi atau manipulasi data, pemalsuan penelitian, sitasi atau dokumen, pengerjaan ujian atau asesmen, penyamaran identitas, bypass anti-plagiarisme, pelanggaran hak cipta, dan aktivitas ilegal. Permintaan yang melanggar dapat ditolak atau dihentikan.</p></section>
    <section><h2 class='text-2xl font-bold text-navy'>Tanggung jawab pelanggan</h2><p class='mt-3 leading-8 text-muted'>Pelanggan wajib memberi informasi yang benar, memiliki hak atas dokumen dan data yang dikirim, memeriksa hasil pendampingan, mematuhi aturan institusi, dan menjaga credential miliknya. Pelanggan tetap bertanggung jawab atas keputusan dan penggunaan output.</p></section>
    <section><h2 class='text-2xl font-bold text-navy'>Revisi, waktu, dan pembayaran</h2><p class='mt-3 leading-8 text-muted'>Ruang lingkup, timeline, dukungan revisi, dan pembayaran manual dikonfirmasi melalui komunikasi resmi. Perubahan kebutuhan dapat memengaruhi waktu dan biaya. Versi awal tidak menyediakan membership, invoice otomatis, payment gateway, atau chat internal.</p></section>
    <section><h2 class='text-2xl font-bold text-navy'>Perubahan dan pembatalan</h2><p class='mt-3 leading-8 text-muted'>Perubahan kebutuhan atau pembatalan harus dikomunikasikan secepatnya. Dampaknya terhadap jadwal, pekerjaan yang sudah dilakukan, dan biaya dibahas berdasarkan ruang lingkup yang telah disepakati; form konsultasi awal bukan persetujuan komersial otomatis.</p></section>
    <section><h2 class='text-2xl font-bold text-navy'>Dokumen dan arsip</h2><p class='mt-3 leading-8 text-muted'>Dokumen proyek dikelola dengan versioning dan soft delete. Pelanggan mengunggah versi baru tanpa menimpa versi lama. Penghapusan permanen hanya dapat dilakukan admin sesuai retensi dan audit yang berlaku.</p></section>
    <section><h2 class='text-2xl font-bold text-navy'>Batas tanggung jawab</h2><p class='mt-3 leading-8 text-muted'>Kami berupaya menjalankan pendampingan sesuai ruang lingkup yang disepakati, tetapi keputusan akademik, publikasi, penggunaan hasil, serta dampak dari data atau informasi yang diberikan tetap berada pada pihak yang berwenang dan pelanggan. Tidak ada jaminan nilai, kelulusan, publikasi, atau hasil tertentu.</p></section>
    <aside class='rounded-2xl border border-gold/30 bg-gold/10 p-5 text-sm leading-7 text-charcoal'><strong>Catatan:</strong> halaman ini bukan nasihat hukum dan harus ditinjau kembali bersama identitas pengelola serta ketentuan komersial final sebelum deployment production.</aside>
</article></section>
@endsection
