@extends('layouts.public')
@section('title', 'Konsultasi Proyek Akademik dan Aplikasi | Jokiinlah')
@section('description', 'Ajukan kebutuhan konsultasi penelitian, analisis data, paper, website, mobile, desktop, dashboard, atau sistem informasi.')
@section('content')
@php($minimumDeadline = now(config('jokiinlah.display_timezone'))->toDateString())
<section class='bg-navy py-16 text-white'><div class='container-public grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end'><div><h1 class='text-balance text-4xl font-bold sm:text-5xl'>Ceritakan Kebutuhan Anda</h1><p class='mt-5 max-w-3xl leading-8 text-white/75'>Informasi yang lengkap membantu kami memberi arahan awal tentang ruang lingkup dan proses. Form ini bukan quotation atau jaminan hasil.</p></div><x-whatsapp-button :url='$whatsAppUrl' /></div></section>
<section class='section-space'><div class='container-public grid gap-8 lg:grid-cols-[0.72fr_1.28fr]'><aside class='space-y-5'><div class='surface-card p-7'><h2 class='text-2xl font-bold text-navy'>Sebelum mengirim</h2><ul class='mt-5 space-y-4 text-sm leading-7 text-muted'><li>✓ Pastikan data dan dokumen dapat Anda gunakan secara sah.</li><li>✓ Jelaskan tujuan, kondisi saat ini, dan output yang dibutuhkan.</li><li>✓ Jangan unggah credential atau informasi yang tidak diperlukan.</li><li>✓ ZIP/RAR disimpan privat dan tidak diekstrak aplikasi.</li></ul></div><div class='surface-card border-rose/40 bg-[#fff8f5] p-7'><h2 class='text-xl font-bold text-navy'>Integritas akademik</h2><p class='mt-3 text-sm leading-7 text-muted'>Kami menolak plagiarisme, ghostwriting untuk diserahkan sebagai karya mandiri, fabrikasi data, pemalsuan penelitian, pengerjaan ujian, dan bypass anti-plagiarisme.</p></div></aside>
<div class='surface-card p-6 sm:p-10'>
    @if($errors->any())<div data-error-summary tabindex='-1' role='alert' aria-live='assertive' class='mb-7 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800'><strong>Periksa kembali formulir.</strong><p class='mt-1'>Terdapat {{ $errors->count() }} isian yang perlu diperbaiki.</p><ul class='mt-3 list-disc space-y-1 pl-5'>@foreach($errors->messages() as $field => $messages)@foreach($messages as $message)<li><a class='font-semibold underline' href='#{{ $field }}'>{{ $message }}</a></li>@endforeach @endforeach</ul></div>@endif
    <form method='POST' action='{{ route('consultations.store') }}' enctype='multipart/form-data' class='space-y-6' x-data='{ submitting: false }' @submit='submitting = true'>@csrf
        <div class='grid gap-5 sm:grid-cols-2'><x-form-input name='name' label='Nama lengkap' required autocomplete='name' /><x-form-input name='email' label='Email' type='email' required autocomplete='email' /></div>
        <div class='grid gap-5 sm:grid-cols-2'><x-form-input name='phone' label='Nomor WhatsApp' required autocomplete='tel' inputmode='tel' placeholder='08xxxxxxxxxx' hint='Gunakan nomor Indonesia, misalnya 0812 3456 7890.' /><x-form-select name='service_id' label='Jenis layanan' required><option value=''>Pilih layanan</option>@foreach($services as $service)<option value='{{ $service->id }}' @selected((string) old('service_id', request('service')) === (string) $service->id)>{{ $service->name }}</option>@endforeach</x-form-select></div>
        <x-form-input name='project_title' label='Judul atau nama proyek' required maxlength='180' />
        <x-form-textarea name='description' label='Deskripsi kebutuhan' required hint='Minimal 30 karakter. Jangan sertakan password, API key, atau data yang tidak relevan.' />
        <div class='grid gap-5 sm:grid-cols-2'><x-form-input name='deadline' label='Deadline (opsional)' type='date' :min='$minimumDeadline' hint='Tanggal diproses sebagai akhir hari zona Asia/Jakarta.' /><x-form-input name='technology' label='Teknologi yang diinginkan (opsional)' maxlength='255' /></div>
        <x-form-input name='budget' label='Estimasi anggaran (opsional)' type='number' min='0' step='1000' hint='Hanya informasi awal, bukan quotation otomatis.' />
        <x-form-file name='attachment' label='Dokumen awal (opsional)' accept='.pdf,.doc,.docx,.xls,.xlsx,.csv,.zip,.rar,.jpg,.jpeg,.png,.webp' hint='Maksimal 20 MB. File disimpan pada private storage.' />
        <div class='absolute -left-[10000px] top-auto h-px w-px overflow-hidden' aria-hidden='true'><label for='website'>Website</label><input id='website' name='website' type='text' tabindex='-1' autocomplete='off'></div>
        <x-form-checkbox name='privacy' required>Saya menyetujui <a class='font-bold underline' href='{{ route('privacy') }}' target='_blank' rel='noopener noreferrer'>Kebijakan Privasi</a> dan pemrosesan data untuk menangani konsultasi.</x-form-checkbox>
        <x-form-checkbox name='academic_integrity' required>Saya menyetujui <a class='font-bold underline' href='{{ route('terms') }}' target='_blank' rel='noopener noreferrer'>Syarat dan Ketentuan</a> dan memahami layanan hanya untuk konsultasi, pendampingan, pembelajaran, editing, analisis data yang sah, serta pengembangan perangkat lunak; bukan plagiarisme, fabrikasi data, pemalsuan, pengerjaan ujian, atau bypass anti-plagiarisme.</x-form-checkbox>
        <x-primary-button type='submit' class='w-full sm:w-auto' x-bind:disabled='submitting'><span x-show='!submitting'>Kirim Permintaan Konsultasi</span><span x-cloak x-show='submitting'>Mengirim permintaan…</span></x-primary-button>
    </form>
</div></div></section>
@endsection
