@extends('layouts.public')
@section('title', 'Pendampingan Akademik & Pengembangan Aplikasi | Jokiinlah')
@section('description', 'Konsultasi penelitian, analisis data, paper, website, mobile, desktop, dashboard, dan sistem informasi melalui proses profesional dan terstruktur.')

@section('content')
<section class='hero-grid relative overflow-hidden bg-navy py-20 text-white sm:py-28 lg:py-32'>
    <div class='pointer-events-none absolute -right-24 top-12 h-80 w-80 rounded-full border border-gold/25'></div><div class='decor-orbit pointer-events-none absolute right-20 top-28 h-44 w-44 rounded-full border border-rose/30'></div>
    <div class='container-public relative grid items-center gap-14 lg:grid-cols-[1.2fr_0.8fr]'>
        <div class='min-w-0' data-reveal><p class='mb-5 text-xs font-bold uppercase tracking-[0.24em] text-rose'>Pendampingan Akademik & Digital</p><h1 class='text-balance text-3xl font-bold leading-[1.12] sm:text-5xl sm:leading-[1.08] lg:text-6xl'>Pendampingan Akademik dan <span class='text-gold'>Pengembangan Aplikasi</span> yang Profesional</h1><p class='mt-7 max-w-2xl text-base leading-8 text-white/75 sm:text-lg'>Konsultasikan kebutuhan penelitian, analisis data, paper, website, aplikasi mobile, desktop, dan sistem informasi melalui proses yang jelas dan terstruktur.</p><div class='mt-9 flex flex-col gap-3 sm:flex-row'><x-primary-button :href="route('contact.index')">Konsultasi Sekarang</x-primary-button><x-secondary-button :href="route('services.index')">Lihat Layanan</x-secondary-button><x-whatsapp-button :url='$whatsAppUrl' label='WhatsApp' /></div></div>
        <div class='relative mx-auto w-full max-w-md' data-reveal><div class='absolute inset-8 rounded-full bg-gold/15 blur-3xl'></div><div class='relative rounded-[2rem] border border-white/15 bg-white/8 p-8 shadow-2xl backdrop-blur'><div class='rounded-[1.7rem] border border-gold/30 bg-white p-5'><img src='{{ asset('images/logo.webp') }}' alt='Logo Jokiinlah – Pendampingan Akademik dan Digital' width='640' height='640' fetchpriority='high' class='aspect-square w-full rounded-2xl object-cover'></div><div class='mt-5 grid grid-cols-2 gap-3 text-xs font-semibold'><span class='rounded-xl bg-white/10 p-3 text-center'>Akademik</span><span class='rounded-xl bg-white/10 p-3 text-center'>Teknologi</span></div></div></div>
    </div>
</section>

<section class='border-b border-navy/10 bg-white py-8' aria-label='Keunggulan layanan'><div class='container-public grid gap-4 sm:grid-cols-2 lg:grid-cols-3'>@foreach(['Proses kerja transparan', 'Kebutuhan dianalisis terlebih dahulu', 'Dokumen disimpan secara aman', 'Komunikasi terstruktur', 'Pendampingan sesuai kebutuhan', 'Dokumentasi hasil sesuai layanan'] as $benefit)<div class='flex min-h-14 items-center gap-3 rounded-xl bg-cream px-4 py-3 text-sm font-semibold text-navy'><span class='flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-navy text-gold' aria-hidden='true'>✓</span>{{ $benefit }}</div>@endforeach</div></section>

<section class='section-space'><div class='container-public'><x-section-heading eyebrow='Solusi Terarah' title='Layanan akademik dan digital sesuai kebutuhan Anda' description='Setiap kebutuhan ditinjau lebih dahulu agar ruang lingkup, proses, dan output dapat dipahami dengan jelas.' /><div class='mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3'>@forelse($services as $service)<x-service-card :service='$service' />@empty<x-empty-state title='Layanan belum tersedia' />@endforelse</div><div class='mt-10 text-center'><x-primary-button :href="route('services.index')">Jelajahi Semua Layanan</x-primary-button></div></div></section>

<section id='cara-kerja' class='section-space bg-white'><div class='container-public'><x-section-heading eyebrow='Cara Kerja' title='Enam tahap yang jelas dan terstruktur' description='Anda mengetahui posisi kebutuhan sejak konsultasi awal hingga penyelesaian dan dokumentasi.' align='center' /><ol class='mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-3'>@foreach(['Konsultasi kebutuhan', 'Pengumpulan data dan dokumen', 'Analisis ruang lingkup', 'Proses pendampingan atau pengembangan', 'Review dan revisi', 'Penyelesaian dan dokumentasi'] as $index => $step)<li class='surface-card relative p-6' data-reveal><span class='flex h-11 w-11 items-center justify-center rounded-full bg-navy font-bold text-gold'>{{ $index + 1 }}</span><h3 class='mt-5 text-xl font-bold text-navy'>{{ $step }}</h3><p class='mt-2 text-sm leading-7 text-muted'>Tahap dikerjakan dengan komunikasi dan catatan proses yang mudah dipahami.</p></li>@endforeach</ol></div></section>

<section class='section-space bg-navy text-white'><div class='container-public'><x-section-heading eyebrow='Portofolio Pilihan' title='Studi kasus solusi yang terstruktur' description='Studi kasus menggambarkan pendekatan kerja tanpa menampilkan informasi pribadi pelanggan.' /><div class='mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3'>@forelse($portfolios as $portfolio)<x-portfolio-card :portfolio='$portfolio' />@empty<x-empty-state title='Studi kasus sedang disiapkan' />@endforelse</div><div class='mt-10'><x-primary-button :href="route('portfolios.index')">Lihat Portofolio</x-primary-button></div></div></section>

<section class='section-space'><div class='container-public grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-start'><x-section-heading eyebrow='Mengapa Kami' title='Pendekatan profesional, bukan janji yang berlebihan' description='Fokus kami adalah membantu memahami kebutuhan, menata proses, dan menghasilkan output sesuai ruang lingkup yang disepakati.' /><div class='grid gap-4 sm:grid-cols-2'>@foreach(['Pendekatan sesuai kebutuhan', 'Proses dan deadline terstruktur', 'Keamanan dokumen', 'Teknologi yang relevan', 'Dukungan komunikasi', 'Dokumentasi yang jelas'] as $reason)<div class='surface-card p-5 text-sm font-bold text-navy' data-reveal><span class='mr-2 text-gold'>◆</span>{{ $reason }}</div>@endforeach</div></div></section>

@if($testimonials->isNotEmpty())<section class='section-space bg-white'><div class='container-public'><x-section-heading eyebrow='Ulasan' title='Pengalaman menggunakan proses pendampingan' description='Pada development, data demonstrasi ditandai secara jelas dan tidak diposisikan sebagai testimoni pelanggan nyata.' align='center' /><div class='mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3'>@foreach($testimonials as $testimonial)<x-testimonial-card :testimonial='$testimonial' />@endforeach</div></div></section>@endif

<section class='section-space'><div class='container-public grid gap-10 lg:grid-cols-[0.8fr_1.2fr]'><x-section-heading eyebrow='FAQ' title='Pertanyaan yang sering diajukan' description='Temukan informasi awal tentang layanan, keamanan dokumen, proses revisi, dan batasan integritas akademik.' /><div class='surface-card px-6 py-3'>@foreach($faqs as $faq)<x-faq-accordion :faq='$faq' />@endforeach<div class='py-5'><a class='font-bold text-navy underline' href='{{ route('faq.index') }}'>Lihat seluruh FAQ</a></div></div></div></section>

<section class='pb-20'><div class='container-public'><div class='hero-grid overflow-hidden rounded-[2rem] bg-navy px-6 py-12 text-center text-white shadow-2xl sm:px-12 sm:py-16' data-reveal><p class='text-xs font-bold uppercase tracking-[0.2em] text-rose'>Konsultasi Awal</p><h2 class='mt-4 text-balance text-3xl font-bold sm:text-5xl'>Siap Mendiskusikan Proyek Anda?</h2><p class='mx-auto mt-5 max-w-2xl leading-8 text-white/75'>Ceritakan kebutuhan Anda dan dapatkan arahan awal mengenai ruang lingkup serta proses pengerjaan.</p><div class='mt-8 flex flex-col justify-center gap-3 sm:flex-row'><x-primary-button :href="route('contact.index')">Ajukan Konsultasi</x-primary-button><x-whatsapp-button :url='$whatsAppUrl' /></div></div></div></section>
@endsection
