@extends('layouts.public')
@section('title', $service->name.' | Jokiinlah')
@section('description', $service->short_description)
@section('content')
<section class='bg-navy py-16 text-white'><div class='container-public'><x-breadcrumb :items="['Layanan' => route('services.index'), $service->name => null]" /><div class='mt-8 grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end'><div><x-badge>{{ $service->category->label() }}</x-badge><h1 class='mt-5 text-balance text-4xl font-bold sm:text-5xl'>{{ $service->name }}</h1><p class='mt-5 max-w-3xl text-lg leading-8 text-white/75'>{{ $service->short_description }}</p></div><x-primary-button :href="route('contact.index', ['service' => $service->id])">Konsultasikan Layanan Ini</x-primary-button></div></div></section>
<section class='section-space'><div class='container-public grid gap-10 lg:grid-cols-[1.2fr_0.8fr]'><article class='surface-card p-7 sm:p-10'><h2 class='text-3xl font-bold text-navy'>Ruang Lingkup Pendampingan</h2><p class='mt-5 whitespace-pre-line leading-8 text-muted'>{{ $service->description }}</p>@if($service->features)<h2 class='mt-10 text-3xl font-bold text-navy'>Output dan Fitur</h2><ul class='mt-5 grid gap-3 sm:grid-cols-2'>@foreach($service->features as $feature)<li class='flex gap-3 rounded-xl bg-cream p-4 text-sm font-semibold'><span class='text-gold'>✓</span>{{ $feature }}</li>@endforeach</ul>@endif</article><aside class='space-y-6'><div class='surface-card p-7'><h2 class='text-2xl font-bold text-navy'>Teknologi & Pendekatan</h2><div class='mt-5 flex flex-wrap gap-2'>@forelse($service->technologies ?? [] as $technology)<x-badge>{{ $technology }}</x-badge>@empty<p class='text-sm text-muted'>Teknologi ditentukan setelah analisis kebutuhan.</p>@endforelse</div></div><div class='surface-card bg-navy p-7 text-white'><h2 class='text-2xl font-bold'>Mulai dengan konsultasi</h2><p class='mt-3 text-sm leading-7 text-white/70'>Ceritakan tujuan, data yang tersedia, dan target waktu agar arahan awal lebih tepat.</p><div class='mt-5 grid gap-3'><x-primary-button :href="route('contact.index', ['service' => $service->id])">Ajukan Konsultasi</x-primary-button><x-whatsapp-button :url='$whatsAppUrl' label='WhatsApp layanan ini' /></div></div></aside></div></section>
<section class='section-space bg-white'><div class='container-public'><x-section-heading eyebrow='Alur Kerja' title='Proses layanan yang transparan' description='Ruang lingkup dan urutan dapat disesuaikan setelah konsultasi awal.' /><ol class='mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4'>@foreach(['Konsultasi kebutuhan', 'Analisis ruang lingkup', 'Pelaksanaan dan dokumentasi', 'Review serta penyelesaian'] as $index => $step)<li class='rounded-2xl border border-navy/10 bg-cream p-5'><span class='flex h-9 w-9 items-center justify-center rounded-full bg-navy text-sm font-bold text-gold'>{{ $index + 1 }}</span><h3 class='mt-4 text-lg font-bold text-navy'>{{ $step }}</h3></li>@endforeach</ol></div></section>
@if($faqs->isNotEmpty())<section class='section-space'><div class='container-public max-w-4xl'><x-section-heading eyebrow='FAQ Layanan' title='Informasi yang perlu diketahui' /><div class='mt-8 surface-card px-6 py-3'>@foreach($faqs as $faq)<x-faq-accordion :faq='$faq' />@endforeach</div></div></section>@endif
@push('structured-data')<x-structured-data :data="['@context' => 'https://schema.org', '@type' => 'Service', 'name' => $service->name, 'description' => $service->short_description, 'provider' => ['@type' => 'Organization', 'name' => 'Jokiinlah'], 'url' => route('services.show', $service)]" />@endpush
@endsection
